language: java
jdk:
  - openjdk11
branches:
  only:
    - master

cache:
  directories:
    - '$HOME/.me/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

before_install:
  - chmod +x gradlew

before_deploy:
  - mkdir -p before-deploy # zip에 포함시킬 파일들을 담을 디렉토리 생성
  - cp scripts/*.sh before-deploy/
  - cp appspec.yml before-deploy/
  - cp build/libs/*.jar before-deploy/
  - cd before-deploy && zip -r before-deploy *
  - cd ../ && mkdir -p deploy # 상위 디렉토리로 이동 후 deploy 디렉토리 생성
  - mv before-deploy/before-deploy.zip deploy/baedeokcar-springboot2-webservice.zip
#  - zip -r baedeokcar-springboot2-webservice *
#  - mkdir -p deploy
#  - mv  baedeokcar-springboot2-webservice.zip deploy/baedeokcar-springboot2-webservice.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY

    bucket: baedeokcar-springboot-build
    region: ap-northeast-2
    skip_cleanup: true
    acl: private
    local_dir: deploy
    wait-until-deployed: true

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: baedeokcar-springboot-build
    key: baedeokcar-springboot2-webservice.zip
    bundle_type: zip
    application: baedeokcar-springboot2-webservice
    deployment_group: baedeokcar-springboot2-webservice-group
    region: ap-northeast-2
    wait-until-deployed: true


notifications:
  email:
    recipients:
      - ludwings0330@gmail.com
