language: java
jdk:
  - openjdk11
branches:
  only:
    - master

cache:
  directories:
    - '$HOME/.me/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

notifications:
  email:
    recipients:
      -ludwings0330@gmail.com
