language: java
jdk:
  - openjdk11
branches:
  only:
    - master

cache:
  directories:
    - '$HOME/.me/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

notifications:
  email:
    recipients:
      - ludwings0330@gmail.com

before_deploy:
  - zip -r baedeokcar-springboot2-webservice *
  - mkdir -p deploy
  - mv baedeokcar-springboot2-webservice.zip deploy/baedeokcar-springboot2-webservice.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY

    bucket: baedeokcar-springboot-build
    region: ap-northeast-2
    skip_cleanup: true
    acl: private
    local_dir: deploy
    wait-until-deployed: true

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY

    bucket: baedeokcar-springboot-build
    key: baedeokcar-springboot2-webservice.zip

    bundle_type: zip
    application: baedeokcar-springboot2-webservice

    deployment_group: baedeokcar-springboot2-webservice-group

    region: ap-northeast-2
    wait-until-deployed: true